### PR TITLE
Patch for kernel 5.10.xx+

### LINKED ISSUE #8: Current version is not compatible with Raspberry Pi kernel 5.10.xx+
```
From https://github.com/pguyot/wm8960
 = [up to date]      tagtagtag-sound -> origin/tagtagtag-sound
 = [up to date]      master          -> origin/master
Already up to date.
make -C /lib/modules/5.10.11+/build M=/home/pi/wm8960 clean
make[1]: Entering directory '/usr/src/linux-headers-5.10.11+'
make[1]: Leaving directory '/usr/src/linux-headers-5.10.11+'
rm -f tagtagtag-mixerd tagtagtag-mixerd-test
cc -Wall -Werror -lasound -lpthread tagtagtag-mixerd.c -o tagtagtag-mixerd
make -C /lib/modules/5.10.11+/build M=/home/pi/wm8960 modules
make[1]: Entering directory '/usr/src/linux-headers-5.10.11+'
scripts/Makefile.lib:8: 'always' is deprecated. Please use 'always-y' instead
  CC [M]  /home/pi/wm8960/wm8960.o
/home/pi/wm8960/wm8960.c: In function ‘wm8960_configure_clocking’:
/home/pi/wm8960/wm8960.c:745:15: error: implicit declaration of function ‘snd_soc_component_read32’; did you mean ‘snd_soc_component_read’? [-Werror=implicit-function-declaration]
  u16 iface1 = snd_soc_component_read32(component, WM8960_IFACE1);
               ^~~~~~~~~~~~~~~~~~~~~~~~
               snd_soc_component_read
/home/pi/wm8960/wm8960.c:745:6: warning: unused variable ‘iface1’ [-Wunused-variable]
  u16 iface1 = snd_soc_component_read32(component, WM8960_IFACE1);
      ^~~~~~
/home/pi/wm8960/wm8960.c: At top level:
/home/pi/wm8960/wm8960.c:1318:3: error: ‘const struct snd_soc_dai_ops’ has no member named ‘digital_mute’
  .digital_mute = wm8960_mute,
   ^~~~~~~~~~~~
/home/pi/wm8960/wm8960.c:1318:18: error: initialization of ‘int (*)(struct snd_pcm_substream *, struct snd_soc_dai *)’ from incompatible pointer type ‘int (*)(struct snd_soc_dai *, int)’ [-Werror=incompatible-pointer-types]
  .digital_mute = wm8960_mute,
                  ^~~~~~~~~~~
/home/pi/wm8960/wm8960.c:1318:18: note: (near initialization for ‘wm8960_dai_ops.prepare’)
cc1: some warnings being treated as errors
make[2]: *** [scripts/Makefile.build:279: /home/pi/wm8960/wm8960.o] Error 1
make[1]: *** [Makefile:1808: /home/pi/wm8960] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-5.10.11+'
make: *** [Makefile:17: all] Error 2
```

### PR DESCRIPTION
**Pull request by f-laurens**
Resolves #8.
Patch wm8960.c to make it compatible with kernel 5.10.11+.

### CODE REVIEW

**Comment by pguyot** [comment]
Thank you. As mentioned elsewhere, we need a conditional to compile on 4.x kernels.

**Comment by f-laurens** [comment]
> Thank you. As mentioned elsewhere, we need a conditional to compile on 4.x kernels.

Indeed.
In order to do this properly, do you have a reference on the "standard" way to handle this in Linux drivers?
I.e.: If the kernel version dependant code is tagged wih `#if XXX`:
- what would be the proper naming for `XXX`?
- how to set it up correctly in the Makefile for the driver?

**Comment by guilhem** [comment]
@f-laurens https://stackoverflow.com/a/16721774 ?

**Comment by pguyot** [comment]
Yup, it's what I implemented here as well as implementing CI.
https://github.com/pguyot/wm8960/tree/test-ci

**Comment by f-laurens** [comment]
Thanks!
Do you intend to push these changes to the `tagtagtag-sound` branch, so that they are be useable by pynab and this PR may be closed?

**Comment by pguyot** [comment]
Patch was merged in #10

**Comment by f-laurens** [comment]
Thanks!

**Pull request closed without merging**
